apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pricelist
  namespace: openshift-gitops
spec:
  destination:
    namespace: pricelist
    server: 'https://kubernetes.default.svc'
  project: dev
  source:
    path: 'pricelist'
    repoURL: 'https://github.com/achieris/gitops-examples.git'
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
  - group: route.openshift.io
    kind: Route
    jsonPointers: 
    - /spec/host
