apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: openshift-gitops-placementrule
  namespace: openshift-gitops
  labels:
    app: argocd
spec:
  clusterConditions:
    - type: ManagedClusterConditionAvailable
      status: "True"
  clusterReplicas: 1
  clusterSelector:
    matchExpressions:
    - key: environment
      operator: In
      values:
      - lab01
      - lab02
